#!/bin/bash

# Lighthouse Manual Testing Guide
# Run these commands in your terminal to verify optimizations

echo "═══════════════════════════════════════════════════════════════════════"
echo "LIGHTHOUSE PERFORMANCE VERIFICATION GUIDE"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""

# Step 1: Build
echo "STEP 1: Build Production"
echo "─────────────────────────────────────────────────────────────────────"
echo "$ npm run build"
echo ""
echo "Expected: Build should complete in ~2 seconds"
echo ""

# Step 2: Start server
echo "STEP 2: Start Production Server"
echo "─────────────────────────────────────────────────────────────────────"
echo "$ npm start"
echo ""
echo "Expected: Server running on http://localhost:3000"
echo ""

# Step 3: Run Lighthouse in Chrome
echo "STEP 3: Run Lighthouse Audit in Chrome"
echo "─────────────────────────────────────────────────────────────────────"
echo "1. Open Chrome browser"
echo "2. Navigate to http://localhost:3000"
echo "3. Press F12 to open DevTools"
echo "4. Click on 'Lighthouse' tab"
echo "5. Click 'Analyze page load'"
echo "6. Wait ~5 minutes for audit to complete"
echo ""

# Step 4: Check scores
echo "STEP 4: Expected Scores"
echo "─────────────────────────────────────────────────────────────────────"
echo "✅ Performance:      92-96 (Goal: 90+)"
echo "✅ Accessibility:    95-98"
echo "✅ Best Practices:   90-95"
echo "✅ SEO:              90-95"
echo ""

# Step 5: Verify optimizations
echo "STEP 5: Verify Optimizations in DevTools"
echo "─────────────────────────────────────────────────────────────────────"
echo "Network Tab:"
echo "  • Filter by 'Images'"
echo "  • Should see .webp files loading (414 KiB total)"
echo "  • Should NOT see large PNG files"
echo ""
echo "Coverage Tab:"
echo "  • Unused JavaScript: < 100 KiB (from CSS/deferred sections)"
echo "  • Unused CSS: < 50 KiB"
echo ""
echo "Performance Tab:"
echo "  • FCP (First Contentful Paint): < 1.5s"
echo "  • LCP (Largest Contentful Paint): < 2.0s"
echo "  • CLS (Cumulative Layout Shift): < 0.1"
echo ""

# Step 6: Check issues
echo "STEP 6: Check for Issues"
echo "─────────────────────────────────────────────────────────────────────"
echo "✅ No render-blocking CSS warnings"
echo "✅ No unused JavaScript warnings (below 100 KiB)"
echo "✅ No image optimization warnings"
echo "✅ No font loading warnings (system fonts)"
echo "✅ Cache headers configured (1 year for images)"
echo ""

echo "═══════════════════════════════════════════════════════════════════════"
echo "QUICK VERIFICATION CHECKLIST"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
echo "Run these commands:"
echo ""
echo "# 1. Kill any existing process"
echo "pkill -f 'next start' || true"
echo ""
echo "# 2. Build"
echo "npm run build"
echo ""
echo "# 3. Start server"
echo "npm start"
echo ""
echo "# 4. In ANOTHER terminal, check image files"
echo "ls -lh public/image/*.webp | wc -l  # Should show 8"
echo "du -sh public/image                 # Should show ~600 KiB total"
echo ""
echo "# 5. Verify cache headers"
echo "curl -I http://localhost:3000/image/Project1.webp | grep Cache"
echo ""
echo "# 6. Open browser and run Lighthouse audit"
echo "open http://localhost:3000"
echo ""
echo "═══════════════════════════════════════════════════════════════════════"
echo ""
